from app.errors.base_error import BaseError


class ResourceAlreadyInUseError(BaseError):
    pass
